name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: assignment1
      id: assignment1
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: assignment1
        setup-command: curl -fsSL https://raw.githubusercontent.com/cppclass-37275-template/scoring/main/scoring1.sh
          -o scoring1.sh && chmod +x scoring1.sh && g++ main.cpp -o main
        command: "./scoring1.sh"
        timeout: 10
        max-score: 20
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        ASSIGNMENT1_RESULTS: "${{steps.assignment1.outputs.result}}"
      with:
        runners: assignment1
